import { Poppins } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/components/ReduxProvider/ReduxProvider";
import { Toaster } from "react-hot-toast";

import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "SRS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="dark hydrated antialiased"
      suppressHydrationWarning
    >
      <body className={poppins.className}>
        <ReduxProvider>
          <ThemeRegistry>
            {children}
            <Toaster
              position="top-right"
              toastOptions={{
                duration: 4000,
              }}
            />
          </ThemeRegistry>
        </ReduxProvider>
      </body>
    </html>
  );
}
