import { Poppins } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/components/ReduxProvider/ReduxProvider";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "SRS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="dark hydrated antialiased"
      suppressHydrationWarning
    >
      <body className={poppins.className}>
        <ReduxProvider>
          {children}
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 4000,
            }}
          />
        </ReduxProvider>
      </body>
    </html>
  );
}
